import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "./component/Navigation";
import Footer from './component/Footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-12'>
              </div>
            </div>
        <Navigation />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
